env:
 - RACKET_VERSION=6.1
 - RACKET_VERSION=HEAD

before_install:
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash

script:
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test -x .
